// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOi7La-JUk-j5zEL-sx2pmBMSWGGdk8wI',
    appId: '1:589281262933:web:c82026fd8b57659bc103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    authDomain: 'nerdesinytu.firebaseapp.com',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
    measurementId: 'G-58LF2JP9BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7NrU4L4N_o4U8mYD9RQbJTXs7fdNU7T8',
    appId: '1:589281262933:android:84fc2c680cfea023c103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRbzBZ9emSMD8qwSXMsGqkbqfLRnY6yKw',
    appId: '1:589281262933:ios:e452b925cd5f0e2dc103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
    iosBundleId: 'com.example.nerdesinYtu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRbzBZ9emSMD8qwSXMsGqkbqfLRnY6yKw',
    appId: '1:589281262933:ios:de2a9098978067c5c103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
    iosBundleId: 'com.example.nerdesinYtu.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOi7La-JUk-j5zEL-sx2pmBMSWGGdk8wI',
    appId: '1:589281262933:web:9795b2d4091a9100c103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    authDomain: 'nerdesinytu.firebaseapp.com',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
    measurementId: 'G-VYLFRXZLSZ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDOi7La-JUk-j5zEL-sx2pmBMSWGGdk8wI',
    appId: '1:589281262933:web:cc5630a48d7c2303c103dc',
    messagingSenderId: '589281262933',
    projectId: 'nerdesinytu',
    authDomain: 'nerdesinytu.firebaseapp.com',
    databaseURL: 'https://nerdesinytu-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nerdesinytu.appspot.com',
    measurementId: 'G-NNH63J5X8F',
  );
}
