import 'package:flutter/material.dart';
import 'package:ionicons/ionicons.dart';

List<IconData> randomIcon = [
  Icons.account_balance,
  Icons.ac_unit,
  Icons.back_hand,
  Icons.cake_outlined,
  Icons.dark_mode_outlined,
  Icons.edit_location_alt_outlined,
  Icons.favorite_border,
  Icons.gavel,
  Icons.hail,
  Icons.ice_skating_outlined,
  Icons.join_inner_sharp,
  Icons.kayaking,
  Icons.key_outlined,
  Icons.label_important_outline,
  Icons.map,
  Icons.nature_people,
  Icons.paid_outlined,
  Icons.radio,
  Icons.tapas_outlined,
  Icons.yard_outlined,
  Icons.zoom_in,
  Icons.verified_outlined,
  Icons.warning_amber,
  Icons.qr_code_2,
  Icons.warehouse_rounded,
  Icons.satellite_alt,
  // yeni package
  Ionicons.heart_outline,
  Ionicons.analytics,
  Ionicons.bag_add_outline,
  Ionicons.cafe,
  Ionicons.diamond_outline,
  Ionicons.earth_outline,
  Ionicons.rocket,
  Ionicons.person_circle_outline,
  Ionicons.telescope_outline,
  Ionicons.paper_plane_outline,
  Ionicons.laptop_outline,
  Ionicons.open_outline,
  Ionicons.shirt_outline,
  Ionicons.ice_cream_outline,
  Ionicons.flower_outline,
  Ionicons.library_outline,
];
